--------------------------------------------------------
-- Archivo creado  - martes-mayo-26-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_MAQUINA
--------------------------------------------------------

   CREATE SEQUENCE  "VENDING_MACHINE"."SEQ_MAQUINA"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence SEQ_PRODUCTO
--------------------------------------------------------

   CREATE SEQUENCE  "VENDING_MACHINE"."SEQ_PRODUCTO"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 10 NOCACHE  NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence SEQ_PUNTOVENTA
--------------------------------------------------------

   CREATE SEQUENCE  "VENDING_MACHINE"."SEQ_PUNTOVENTA"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Sequence SEQ_STOCKMAQ
--------------------------------------------------------

   CREATE SEQUENCE  "VENDING_MACHINE"."SEQ_STOCKMAQ"  MINVALUE 1 MAXVALUE 999999999999 INCREMENT BY 1 START WITH 20 NOCACHE  NOORDER  NOCYCLE
--------------------------------------------------------
--  DDL for Table T_MAQUINA
--------------------------------------------------------

  CREATE TABLE "VENDING_MACHINE"."T_MAQUINA" 
   (	"ID_MAQUINA" NUMBER(12,0) NOT NULL ENABLE, 
	"PTV_ID_PUNTOVENTA" NUMBER(12,0) NOT NULL ENABLE, 
	"D_DESCRIPCION" VARCHAR2(150), 
	"L_BORRADO" VARCHAR2(1) DEFAULT 'N', 
	"U_CREACION" VARCHAR2(50) NOT NULL ENABLE, 
	"F_CREACION" DATE NOT NULL ENABLE, 
	"U_MODIFICACION" VARCHAR2(50) NOT NULL ENABLE, 
	"F_MODIFICACION" DATE NOT NULL ENABLE, 
	 CONSTRAINT "MAQ_PK" PRIMARY KEY ("ID_MAQUINA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "MAQ_LBORRADO_CK" CHECK (L_BORRADO IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "MAQ_PTV_FK" FOREIGN KEY ("PTV_ID_PUNTOVENTA")
	  REFERENCES "VENDING_MACHINE"."T_PUNTOVENTA" ("ID_PUNTOVENTA") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "VENDING_MACHINE"."T_MAQUINA"."ID_MAQUINA" IS 'Identificador unico de la m�quina'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_MAQUINA"."PTV_ID_PUNTOVENTA" IS 'Identificador del punto de venta al que pertenece la m�quina'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_MAQUINA"."D_DESCRIPCION" IS 'Descripci�n de la m�quina'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_MAQUINA"."L_BORRADO" IS 'Borrado logico (S/N)'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_MAQUINA"."U_CREACION" IS 'Identificador del usuario de grabaci�n'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_MAQUINA"."F_CREACION" IS 'Fecha y hora de grabaci�n'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_MAQUINA"."U_MODIFICACION" IS 'Identificador del usuario que ha realizado la �ltima modificaci�n'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_MAQUINA"."F_MODIFICACION" IS 'Fecha y hora de la �ltima modificaci�n'
   COMMENT ON TABLE "VENDING_MACHINE"."T_MAQUINA"  IS '[MAQ] Tabla que define las m�quinas expendedoras asociadas a un punto de venta'
--------------------------------------------------------
--  DDL for Table T_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "VENDING_MACHINE"."T_PRODUCTO" 
   (	"ID_PRODUCTO" NUMBER(12,0) NOT NULL ENABLE, 
	"C_PRODUCTO" VARCHAR2(50) NOT NULL ENABLE, 
	"D_DESCRIPCION" VARCHAR2(500), 
	"I_PRECIO" NUMBER(10,2), 
	"L_BORRADO" VARCHAR2(1) DEFAULT 'N', 
	"U_CREACION" VARCHAR2(50) NOT NULL ENABLE, 
	"F_CREACION" DATE NOT NULL ENABLE, 
	"U_MODIFICACION" VARCHAR2(50) NOT NULL ENABLE, 
	"F_MODIFICACION" DATE NOT NULL ENABLE, 
	 CONSTRAINT "PROD_PK" PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "PRO_LBORRADO_CK" CHECK (L_BORRADO IN ('S', 'N')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "VENDING_MACHINE"."T_PRODUCTO"."ID_PRODUCTO" IS 'Identificador unico del producto'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_PRODUCTO"."C_PRODUCTO" IS 'Codigo del producto'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_PRODUCTO"."D_DESCRIPCION" IS 'Descripci�n del producto'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_PRODUCTO"."I_PRECIO" IS 'Precio unitario de venta del producto'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_PRODUCTO"."L_BORRADO" IS 'Borrado logico (S/N)'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_PRODUCTO"."U_CREACION" IS 'Identificador del usuario de grabaci�n'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_PRODUCTO"."F_CREACION" IS 'Fecha y hora de grabaci�n'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_PRODUCTO"."U_MODIFICACION" IS 'Identificador del usuario que ha realizado la �ltima modificaci�n'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_PRODUCTO"."F_MODIFICACION" IS 'Fecha y hora de la �ltima modificaci�n'
   COMMENT ON TABLE "VENDING_MACHINE"."T_PRODUCTO"  IS '[PROD] Tabla que define el cat�logo de productos disponibles para su venta en las m�quinas'
--------------------------------------------------------
--  DDL for Table T_PUNTOVENTA
--------------------------------------------------------

  CREATE TABLE "VENDING_MACHINE"."T_PUNTOVENTA" 
   (	"ID_PUNTOVENTA" NUMBER(12,0) NOT NULL ENABLE, 
	"C_PUNTOVENTA" VARCHAR2(10) NOT NULL ENABLE, 
	"D_DESCRIPCION" VARCHAR2(150), 
	"L_BORRADO" VARCHAR2(1) DEFAULT 'N', 
	"U_CREACION" VARCHAR2(50) NOT NULL ENABLE, 
	"F_CREACION" DATE NOT NULL ENABLE, 
	"U_MODIFICACION" VARCHAR2(50) NOT NULL ENABLE, 
	"F_MODIFICACION" DATE NOT NULL ENABLE, 
	 CONSTRAINT "PTV_PK" PRIMARY KEY ("ID_PUNTOVENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "PTV_LBORRADO_CK" CHECK (L_BORRADO IN ('S', 'N')) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "VENDING_MACHINE"."T_PUNTOVENTA"."ID_PUNTOVENTA" IS 'Identificador unico del punto de venta'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_PUNTOVENTA"."C_PUNTOVENTA" IS 'Codigo del punto de venta'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_PUNTOVENTA"."D_DESCRIPCION" IS 'Descripci�n del punto de venta'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_PUNTOVENTA"."L_BORRADO" IS 'Borrado logico (S/N)'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_PUNTOVENTA"."U_CREACION" IS 'Identificador del usuario de grabaci�n'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_PUNTOVENTA"."F_CREACION" IS 'Fecha y hora de grabaci�n'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_PUNTOVENTA"."U_MODIFICACION" IS 'Identificador del usuario que ha realizado la �ltima modificaci�n'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_PUNTOVENTA"."F_MODIFICACION" IS 'Fecha y hora de la �ltima modificaci�n'
   COMMENT ON TABLE "VENDING_MACHINE"."T_PUNTOVENTA"  IS '[PTV] Tabla que define los puntos de venta donde se ubican las m�quinas'
--------------------------------------------------------
--  DDL for Table T_STOCKMAQ
--------------------------------------------------------

  CREATE TABLE "VENDING_MACHINE"."T_STOCKMAQ" 
   (	"ID_STOCKMAQ" NUMBER(12,0) NOT NULL ENABLE, 
	"MAQ_ID_MAQUINA" NUMBER(12,0) NOT NULL ENABLE, 
	"PROD_ID_PRODUCTO" NUMBER(12,0) NOT NULL ENABLE, 
	"N_CANTIDAD" NUMBER(10,0) NOT NULL ENABLE, 
	"L_BORRADO" VARCHAR2(1) DEFAULT 'N', 
	"U_CREACION" VARCHAR2(50) NOT NULL ENABLE, 
	"F_CREACION" DATE NOT NULL ENABLE, 
	"U_MODIFICACION" VARCHAR2(50) NOT NULL ENABLE, 
	"F_MODIFICACION" DATE NOT NULL ENABLE, 
	 CONSTRAINT "STK_PK" PRIMARY KEY ("ID_STOCKMAQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "STK_LBORRADO_CK" CHECK (L_BORRADO IN ('S', 'N')) ENABLE, 
	 CONSTRAINT "STK_MAQ_FK" FOREIGN KEY ("MAQ_ID_MAQUINA")
	  REFERENCES "VENDING_MACHINE"."T_MAQUINA" ("ID_MAQUINA") ENABLE, 
	 CONSTRAINT "STK_PROD_FK" FOREIGN KEY ("PROD_ID_PRODUCTO")
	  REFERENCES "VENDING_MACHINE"."T_PRODUCTO" ("ID_PRODUCTO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 

   COMMENT ON COLUMN "VENDING_MACHINE"."T_STOCKMAQ"."ID_STOCKMAQ" IS 'Identificador unico del registro de stock'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_STOCKMAQ"."MAQ_ID_MAQUINA" IS 'Identificador de la maquina a la que pertenece el stock'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_STOCKMAQ"."PROD_ID_PRODUCTO" IS 'Identificador del producto del que se registra el stock'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_STOCKMAQ"."N_CANTIDAD" IS 'Cantidad de unidades disponibles del producto en la maquina'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_STOCKMAQ"."L_BORRADO" IS 'Borrado logico (S/N)'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_STOCKMAQ"."U_CREACION" IS 'Identificador del usuario de grabaci�n'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_STOCKMAQ"."F_CREACION" IS 'Fecha y hora de grabaci�n'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_STOCKMAQ"."U_MODIFICACION" IS 'Identificador del usuario que ha realizado la �ltima modificaci�n'
   COMMENT ON COLUMN "VENDING_MACHINE"."T_STOCKMAQ"."F_MODIFICACION" IS 'Fecha y hora de la �ltima modificaci�n'
   COMMENT ON TABLE "VENDING_MACHINE"."T_STOCKMAQ"  IS '[STK] Tabla que registra el stock de cada producto en cada maquina expendedora'
REM INSERTING into VENDING_MACHINE.T_MAQUINA
SET DEFINE OFF;
Insert into VENDING_MACHINE.T_MAQUINA (ID_MAQUINA,PTV_ID_PUNTOVENTA,D_DESCRIPCION,L_BORRADO,U_CREACION,F_CREACION,U_MODIFICACION,F_MODIFICACION) values ('1','1','Máquina 1 - Sol','N','VENDING_MACHINE',to_date('20/05/26','DD/MM/RR'),'VENDING_MACHINE',to_date('20/05/26','DD/MM/RR'));
Insert into VENDING_MACHINE.T_MAQUINA (ID_MAQUINA,PTV_ID_PUNTOVENTA,D_DESCRIPCION,L_BORRADO,U_CREACION,F_CREACION,U_MODIFICACION,F_MODIFICACION) values ('2','1','Máquina 2 - Sol','N','VENDING_MACHINE',to_date('20/05/26','DD/MM/RR'),'VENDING_MACHINE',to_date('20/05/26','DD/MM/RR'));
Insert into VENDING_MACHINE.T_MAQUINA (ID_MAQUINA,PTV_ID_PUNTOVENTA,D_DESCRIPCION,L_BORRADO,U_CREACION,F_CREACION,U_MODIFICACION,F_MODIFICACION) values ('3','2','Máquina 1 - Atocha','N','VENDING_MACHINE',to_date('20/05/26','DD/MM/RR'),'VENDING_MACHINE',to_date('20/05/26','DD/MM/RR'));
Insert into VENDING_MACHINE.T_MAQUINA (ID_MAQUINA,PTV_ID_PUNTOVENTA,D_DESCRIPCION,L_BORRADO,U_CREACION,F_CREACION,U_MODIFICACION,F_MODIFICACION) values ('4','2','Máquina 2 - Atocha','N','VENDING_MACHINE',to_date('20/05/26','DD/MM/RR'),'VENDING_MACHINE',to_date('20/05/26','DD/MM/RR'));
REM INSERTING into VENDING_MACHINE.T_PRODUCTO
SET DEFINE OFF;
Insert into VENDING_MACHINE.T_PRODUCTO (ID_PRODUCTO,C_PRODUCTO,D_DESCRIPCION,I_PRECIO,L_BORRADO,U_CREACION,F_CREACION,U_MODIFICACION,F_MODIFICACION) values ('1','RAM','Un simple módulo de RAM de alrededor de 1990. Intenta comprarlo, si puedes...','1,5','N','VENDING_MACHINE',to_date('20/05/26','DD/MM/RR'),'VENDING_MACHINE',to_date('25/05/26','DD/MM/RR'));
Insert into VENDING_MACHINE.T_PRODUCTO (ID_PRODUCTO,C_PRODUCTO,D_DESCRIPCION,I_PRECIO,L_BORRADO,U_CREACION,F_CREACION,U_MODIFICACION,F_MODIFICACION) values ('2','Tarjeta de Steam','Tarjeta regalo de Steam de unos 20€. ¡Apoya el capitalismo con esta compra!','1','N','VENDING_MACHINE',to_date('20/05/26','DD/MM/RR'),'VENDING_MACHINE',to_date('25/05/26','DD/MM/RR'));
Insert into VENDING_MACHINE.T_PRODUCTO (ID_PRODUCTO,C_PRODUCTO,D_DESCRIPCION,I_PRECIO,L_BORRADO,U_CREACION,F_CREACION,U_MODIFICACION,F_MODIFICACION) values ('3','Gato ninja del Animal Crossing','No me preguntes por qué.','1,2','N','VENDING_MACHINE',to_date('20/05/26','DD/MM/RR'),'VENDING_MACHINE',to_date('25/05/26','DD/MM/RR'));
Insert into VENDING_MACHINE.T_PRODUCTO (ID_PRODUCTO,C_PRODUCTO,D_DESCRIPCION,I_PRECIO,L_BORRADO,U_CREACION,F_CREACION,U_MODIFICACION,F_MODIFICACION) values ('4','Marlboro','Un paquete de refrescante alquitrán. Disfruta de los pequeños placeres de la vida.','5,5','N','VENDING_MACHINE',to_date('25/05/26','DD/MM/RR'),'VENDING_MACHINE',to_date('25/05/26','DD/MM/RR'));
Insert into VENDING_MACHINE.T_PRODUCTO (ID_PRODUCTO,C_PRODUCTO,D_DESCRIPCION,I_PRECIO,L_BORRADO,U_CREACION,F_CREACION,U_MODIFICACION,F_MODIFICACION) values ('5','Botella de whisky','La cura de todas las penas y el comienzo de otras.','15,99','N','VENDING_MACHINE',to_date('25/05/26','DD/MM/RR'),'VENDING_MACHINE',to_date('25/05/26','DD/MM/RR'));
Insert into VENDING_MACHINE.T_PRODUCTO (ID_PRODUCTO,C_PRODUCTO,D_DESCRIPCION,I_PRECIO,L_BORRADO,U_CREACION,F_CREACION,U_MODIFICACION,F_MODIFICACION) values ('6','Ramen instantáneo','ÑAMI ÑAMI','2,5','N','VENDING_MACHINE',to_date('25/05/26','DD/MM/RR'),'VENDING_MACHINE',to_date('25/05/26','DD/MM/RR'));
REM INSERTING into VENDING_MACHINE.T_PUNTOVENTA
SET DEFINE OFF;
Insert into VENDING_MACHINE.T_PUNTOVENTA (ID_PUNTOVENTA,C_PUNTOVENTA,D_DESCRIPCION,L_BORRADO,U_CREACION,F_CREACION,U_MODIFICACION,F_MODIFICACION) values ('1','PV01','Centro Comercial Sol','N','VENDING_MACHINE',to_date('20/05/26','DD/MM/RR'),'VENDING_MACHINE',to_date('20/05/26','DD/MM/RR'));
Insert into VENDING_MACHINE.T_PUNTOVENTA (ID_PUNTOVENTA,C_PUNTOVENTA,D_DESCRIPCION,L_BORRADO,U_CREACION,F_CREACION,U_MODIFICACION,F_MODIFICACION) values ('2','PV02','Estación Atocha','N','VENDING_MACHINE',to_date('20/05/26','DD/MM/RR'),'VENDING_MACHINE',to_date('20/05/26','DD/MM/RR'));
REM INSERTING into VENDING_MACHINE.T_STOCKMAQ
SET DEFINE OFF;
Insert into VENDING_MACHINE.T_STOCKMAQ (ID_STOCKMAQ,MAQ_ID_MAQUINA,PROD_ID_PRODUCTO,N_CANTIDAD,L_BORRADO,U_CREACION,F_CREACION,U_MODIFICACION,F_MODIFICACION) values ('1','1','1','30','N','VENDING_MACHINE',to_date('20/05/26','DD/MM/RR'),'VENDING_MACHINE',to_date('25/05/26','DD/MM/RR'));
Insert into VENDING_MACHINE.T_STOCKMAQ (ID_STOCKMAQ,MAQ_ID_MAQUINA,PROD_ID_PRODUCTO,N_CANTIDAD,L_BORRADO,U_CREACION,F_CREACION,U_MODIFICACION,F_MODIFICACION) values ('2','1','2','12','N','VENDING_MACHINE',to_date('20/05/26','DD/MM/RR'),'VENDING_MACHINE',to_date('26/05/26','DD/MM/RR'));
Insert into VENDING_MACHINE.T_STOCKMAQ (ID_STOCKMAQ,MAQ_ID_MAQUINA,PROD_ID_PRODUCTO,N_CANTIDAD,L_BORRADO,U_CREACION,F_CREACION,U_MODIFICACION,F_MODIFICACION) values ('4','3','3','88','N','VENDING_MACHINE',to_date('20/05/26','DD/MM/RR'),'VENDING_MACHINE',to_date('26/05/26','DD/MM/RR'));
Insert into VENDING_MACHINE.T_STOCKMAQ (ID_STOCKMAQ,MAQ_ID_MAQUINA,PROD_ID_PRODUCTO,N_CANTIDAD,L_BORRADO,U_CREACION,F_CREACION,U_MODIFICACION,F_MODIFICACION) values ('14','1','4','10','N','VENDING_MACHINE',to_date('25/05/26','DD/MM/RR'),'VENDING_MACHINE',to_date('25/05/26','DD/MM/RR'));
Insert into VENDING_MACHINE.T_STOCKMAQ (ID_STOCKMAQ,MAQ_ID_MAQUINA,PROD_ID_PRODUCTO,N_CANTIDAD,L_BORRADO,U_CREACION,F_CREACION,U_MODIFICACION,F_MODIFICACION) values ('15','1','5','10','N','VENDING_MACHINE',to_date('25/05/26','DD/MM/RR'),'VENDING_MACHINE',to_date('25/05/26','DD/MM/RR'));
Insert into VENDING_MACHINE.T_STOCKMAQ (ID_STOCKMAQ,MAQ_ID_MAQUINA,PROD_ID_PRODUCTO,N_CANTIDAD,L_BORRADO,U_CREACION,F_CREACION,U_MODIFICACION,F_MODIFICACION) values ('16','1','6','10','N','VENDING_MACHINE',to_date('25/05/26','DD/MM/RR'),'VENDING_MACHINE',to_date('25/05/26','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index MAQ_PTV_IDX
--------------------------------------------------------

  CREATE INDEX "VENDING_MACHINE"."MAQ_PTV_IDX" ON "VENDING_MACHINE"."T_MAQUINA" ("PTV_ID_PUNTOVENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index PTV_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDING_MACHINE"."PTV_PK" ON "VENDING_MACHINE"."T_PUNTOVENTA" ("ID_PUNTOVENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index MAQ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDING_MACHINE"."MAQ_PK" ON "VENDING_MACHINE"."T_MAQUINA" ("ID_MAQUINA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index PROD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDING_MACHINE"."PROD_PK" ON "VENDING_MACHINE"."T_PRODUCTO" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index STK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDING_MACHINE"."STK_PK" ON "VENDING_MACHINE"."T_STOCKMAQ" ("ID_STOCKMAQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index STK_PRO_IDX
--------------------------------------------------------

  CREATE INDEX "VENDING_MACHINE"."STK_PRO_IDX" ON "VENDING_MACHINE"."T_STOCKMAQ" ("PROD_ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index STK_MAQ_IDX
--------------------------------------------------------

  CREATE INDEX "VENDING_MACHINE"."STK_MAQ_IDX" ON "VENDING_MACHINE"."T_STOCKMAQ" ("MAQ_ID_MAQUINA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Trigger TR_BI_MAQ01
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDING_MACHINE"."TR_BI_MAQ01" 
   BEFORE INSERT
   ON T_MAQUINA
   FOR EACH ROW
BEGIN
   :NEW.F_CREACION      := SYSDATE;
   :NEW.U_CREACION      := USER;
   :NEW.F_modificacion  := SYSDATE;
   :NEW.U_modificacion  := USER;
END;
ALTER TRIGGER "VENDING_MACHINE"."TR_BI_MAQ01" ENABLE
--------------------------------------------------------
--  DDL for Trigger TR_BI_PRO01
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDING_MACHINE"."TR_BI_PRO01" 
   BEFORE INSERT
   ON T_PRODUCTO
   FOR EACH ROW
BEGIN
   :NEW.F_CREACION      := SYSDATE;
   :NEW.U_CREACION      := USER;
   :NEW.F_MODIFICACION  := SYSDATE;
   :NEW.U_MODIFICACION  := USER;
END;

ALTER TRIGGER "VENDING_MACHINE"."TR_BI_PRO01" ENABLE
--------------------------------------------------------
--  DDL for Trigger TR_BI_PTV01
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDING_MACHINE"."TR_BI_PTV01" 
   BEFORE INSERT
   ON T_PUNTOVENTA
   FOR EACH ROW
BEGIN
   :NEW.F_CREACION      := SYSDATE;
   :NEW.U_CREACION      := USER;
   :NEW.F_MODIFICACION  := SYSDATE;
   :NEW.U_MODIFICACION  := USER;
END;
ALTER TRIGGER "VENDING_MACHINE"."TR_BI_PTV01" ENABLE
--------------------------------------------------------
--  DDL for Trigger TR_BI_STK01
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDING_MACHINE"."TR_BI_STK01" 
   BEFORE INSERT
   ON T_STOCKMAQ
   FOR EACH ROW
BEGIN
   :NEW.F_CREACION      := SYSDATE;
   :NEW.U_CREACION      := USER;
   :NEW.F_MODIFICACION  := SYSDATE;
   :NEW.U_MODIFICACION  := USER;
END;

ALTER TRIGGER "VENDING_MACHINE"."TR_BI_STK01" ENABLE
--------------------------------------------------------
--  DDL for Trigger TR_BU_MAQ02
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDING_MACHINE"."TR_BU_MAQ02" 
   BEFORE UPDATE
   ON T_MAQUINA
   FOR EACH ROW
BEGIN
   :NEW.F_modificacion  := SYSDATE;
   :NEW.U_modificacion  := USER;
END;

ALTER TRIGGER "VENDING_MACHINE"."TR_BU_MAQ02" ENABLE
--------------------------------------------------------
--  DDL for Trigger TR_BU_PRO02
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDING_MACHINE"."TR_BU_PRO02" 
   BEFORE UPDATE
   ON T_PRODUCTO
   FOR EACH ROW
BEGIN
   :NEW.F_MODIFICACION  := SYSDATE;
   :NEW.U_MODIFICACION  := USER;
END;

ALTER TRIGGER "VENDING_MACHINE"."TR_BU_PRO02" ENABLE
--------------------------------------------------------
--  DDL for Trigger TR_BU_PTV02
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDING_MACHINE"."TR_BU_PTV02" 
   BEFORE UPDATE
   ON T_PUNTOVENTA
   FOR EACH ROW
BEGIN
   :NEW.F_MODIFICACI�N  := SYSDATE;
   :NEW.U_MODIFICACI�N  := USER;
END;

ALTER TRIGGER "VENDING_MACHINE"."TR_BU_PTV02" ENABLE
--------------------------------------------------------
--  DDL for Trigger TR_BU_STK02
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDING_MACHINE"."TR_BU_STK02" 
   BEFORE UPDATE
   ON T_STOCKMAQ
   FOR EACH ROW
BEGIN
   :NEW.F_MODIFICACION  := SYSDATE;
   :NEW.U_MODIFICACION  := USER;
END;

ALTER TRIGGER "VENDING_MACHINE"."TR_BU_STK02" ENABLE
--------------------------------------------------------
--  DDL for Package PK_STOCKMAQUINAS
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "VENDING_MACHINE"."PK_STOCKMAQUINAS" AS
  
  FUNCTION FU_OBTENER_STOCK_TOTAL(p_id_producto NUMBER)
    RETURN NUMBER;

  PROCEDURE PR_REPONER_STOCK(
    p_id_maquina   NUMBER,
    p_id_producto  NUMBER,
    p_cantidad     NUMBER
  );

END PK_STOCKMAQUINAS;
--------------------------------------------------------
--  DDL for Package Body PK_STOCKMAQUINAS
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "VENDING_MACHINE"."PK_STOCKMAQUINAS" AS
    
    -- ==================================
    -- ######## STOCK TOTAL ###########
    -- ==================================
    
    FUNCTION FU_OBTENER_STOCK_TOTAL(P_ID_PRODUCTO NUMBER)
        RETURN NUMBER
    IS 
        V_TOTAL NUMBER;
    BEGIN
            SELECT SUM(N_CANTIDAD)
            INTO V_TOTAL
            FROM T_STOCKMAQ
            WHERE PROD_ID_PRODUCTO = P_ID_PRODUCTO;

        RETURN NVL(V_TOTAL, 0);

    END FU_OBTENER_STOCK_TOTAL;

    -- ==================================
    -- ######## REPONER STOCK ###########
    -- ==================================

    PROCEDURE PR_REPONER_STOCK(
        P_ID_MAQUINA NUMBER,
        P_ID_PRODUCTO NUMBER,
        P_CANTIDAD NUMBER
    ) AS
        V_DUMMY NUMBER;
        V_STOCK_ACTUAL NUMBER;
        V_MAQUINA_CONT NUMBER;
        V_PRODUCTO_CONT NUMBER;
        E_INPUT_NEGATIVO EXCEPTION;

    BEGIN 
    -- COMPROBACION INPUT POSITIVO
        IF P_CANTIDAD < 0 THEN
            RAISE_APPLICATION_ERROR(-20001, 'Input negativo');
        END IF;

    -- Validar maquina
        BEGIN 
            SELECT 1 INTO v_dummy
            FROM T_MAQUINA
            WHERE ID_MAQUINA = P_ID_MAQUINA;
            EXCEPTION 
                WHEN NO_DATA_FOUND THEN
                    RAISE_APPLICATION_ERROR(-20002, 'Maquina inexistente');
        END;

    -- Validar producto
        BEGIN 
            SELECT 1 INTO v_dummy
            FROM T_PRODUCTO
            WHERE ID_PRODUCTO = P_ID_PRODUCTO;
            EXCEPTION
                WHEN NO_DATA_FOUND THEN
                    RAISE_APPLICATION_ERROR(-20003, 'Producto inexistente');
        END;
      --
        BEGIN
            SELECT N_CANTIDAD
            INTO V_STOCK_ACTUAL
            FROM T_STOCKMAQ
            WHERE MAQ_ID_MAQUINA = P_ID_MAQUINA
            AND PROD_ID_PRODUCTO = P_ID_PRODUCTO;

            UPDATE T_STOCKMAQ 
            SET N_CANTIDAD = V_STOCK_ACTUAL + P_CANTIDAD 
            WHERE MAQ_ID_MAQUINA = P_ID_MAQUINA 
            AND PROD_ID_PRODUCTO = P_ID_PRODUCTO;

            EXCEPTION
            WHEN NO_DATA_FOUND THEN
                INSERT INTO T_STOCKMAQ
                (ID_STOCKMAQ, MAQ_ID_MAQUINA, PROD_ID_PRODUCTO, N_CANTIDAD)
                VALUES (SEQ_STOCKMAQ.NEXTVAL, P_ID_MAQUINA, P_ID_PRODUCTO, P_CANTIDAD);
        END;



    END PR_REPONER_STOCK;

END PK_STOCKMAQUINAS;
--------------------------------------------------------
--  Constraints for Table T_PUNTOVENTA
--------------------------------------------------------

  ALTER TABLE "VENDING_MACHINE"."T_PUNTOVENTA" ADD CONSTRAINT "PTV_PK" PRIMARY KEY ("ID_PUNTOVENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "VENDING_MACHINE"."T_PUNTOVENTA" MODIFY ("F_MODIFICACION" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_PUNTOVENTA" MODIFY ("U_MODIFICACION" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_PUNTOVENTA" MODIFY ("F_CREACION" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_PUNTOVENTA" MODIFY ("U_CREACION" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_PUNTOVENTA" MODIFY ("C_PUNTOVENTA" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_PUNTOVENTA" MODIFY ("ID_PUNTOVENTA" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_PUNTOVENTA" ADD CONSTRAINT "PTV_LBORRADO_CK" CHECK (L_BORRADO IN ('S', 'N')) ENABLE
--------------------------------------------------------
--  Constraints for Table T_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "VENDING_MACHINE"."T_PRODUCTO" ADD CONSTRAINT "PRO_LBORRADO_CK" CHECK (L_BORRADO IN ('S', 'N')) ENABLE
  ALTER TABLE "VENDING_MACHINE"."T_PRODUCTO" ADD CONSTRAINT "PROD_PK" PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "VENDING_MACHINE"."T_PRODUCTO" MODIFY ("F_MODIFICACION" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_PRODUCTO" MODIFY ("U_MODIFICACION" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_PRODUCTO" MODIFY ("F_CREACION" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_PRODUCTO" MODIFY ("U_CREACION" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_PRODUCTO" MODIFY ("C_PRODUCTO" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_PRODUCTO" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table T_MAQUINA
--------------------------------------------------------

  ALTER TABLE "VENDING_MACHINE"."T_MAQUINA" ADD CONSTRAINT "MAQ_LBORRADO_CK" CHECK (L_BORRADO IN ('S', 'N')) ENABLE
  ALTER TABLE "VENDING_MACHINE"."T_MAQUINA" ADD CONSTRAINT "MAQ_PK" PRIMARY KEY ("ID_MAQUINA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "VENDING_MACHINE"."T_MAQUINA" MODIFY ("F_MODIFICACION" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_MAQUINA" MODIFY ("U_MODIFICACION" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_MAQUINA" MODIFY ("F_CREACION" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_MAQUINA" MODIFY ("U_CREACION" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_MAQUINA" MODIFY ("PTV_ID_PUNTOVENTA" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_MAQUINA" MODIFY ("ID_MAQUINA" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table T_STOCKMAQ
--------------------------------------------------------

  ALTER TABLE "VENDING_MACHINE"."T_STOCKMAQ" ADD CONSTRAINT "STK_LBORRADO_CK" CHECK (L_BORRADO IN ('S', 'N')) ENABLE
  ALTER TABLE "VENDING_MACHINE"."T_STOCKMAQ" ADD CONSTRAINT "STK_PK" PRIMARY KEY ("ID_STOCKMAQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "VENDING_MACHINE"."T_STOCKMAQ" MODIFY ("F_MODIFICACION" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_STOCKMAQ" MODIFY ("U_MODIFICACION" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_STOCKMAQ" MODIFY ("F_CREACION" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_STOCKMAQ" MODIFY ("U_CREACION" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_STOCKMAQ" MODIFY ("N_CANTIDAD" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_STOCKMAQ" MODIFY ("PROD_ID_PRODUCTO" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_STOCKMAQ" MODIFY ("MAQ_ID_MAQUINA" NOT NULL ENABLE)
  ALTER TABLE "VENDING_MACHINE"."T_STOCKMAQ" MODIFY ("ID_STOCKMAQ" NOT NULL ENABLE)
--------------------------------------------------------
--  Ref Constraints for Table T_MAQUINA
--------------------------------------------------------

  ALTER TABLE "VENDING_MACHINE"."T_MAQUINA" ADD CONSTRAINT "MAQ_PTV_FK" FOREIGN KEY ("PTV_ID_PUNTOVENTA")
	  REFERENCES "VENDING_MACHINE"."T_PUNTOVENTA" ("ID_PUNTOVENTA") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table T_STOCKMAQ
--------------------------------------------------------

  ALTER TABLE "VENDING_MACHINE"."T_STOCKMAQ" ADD CONSTRAINT "STK_MAQ_FK" FOREIGN KEY ("MAQ_ID_MAQUINA")
	  REFERENCES "VENDING_MACHINE"."T_MAQUINA" ("ID_MAQUINA") ENABLE
  ALTER TABLE "VENDING_MACHINE"."T_STOCKMAQ" ADD CONSTRAINT "STK_PROD_FK" FOREIGN KEY ("PROD_ID_PRODUCTO")
	  REFERENCES "VENDING_MACHINE"."T_PRODUCTO" ("ID_PRODUCTO") ENABLE
